### ISSUE TITLE
Why not use huggingface generate() and write custom greedy search?

### ISSUE THREAD

**Issue by Moses0h** [project-baize/baize#12]
I'm trying to run batch generation but greedy_search() seems to work only for single input_ids. Curious why you guys implemented greedy_search()?

**Comment by guoday** [comment]
For demo, if you run batch generation, you will need to wait for inference to complete. You can use this [code](https://github.com/tloen/alpaca-lora/blob/e2ed209d3bf83ad8963d185dc97d6cc81bb51bf8/generate.py#L100-L159) for batch generation, it seems more great. We may refer to this to change our code.

**Comment by JetRunner** [comment]
Closing it for now and will add batch inference option in our to-do list.

**Comment by Moses0h** [comment]
writing here because related,

I'm currently using 0 as padding token (correct me if I'm wrong) and left-padding.
However, the more the padding, the generated output becomes more and more weird. 

for example, inputs_ids [0,0,0,0,..... 23,5,143,24, etc...] has weird generated outputs and just [23, 5, 143, 24, etc...] works normally.
