### ISSUE TITLE
Baize repeating answer mutilple times

### ISSUE THREAD

**Issue by LxDevelop** [project-baize/baize#5]
<img width="877" alt="do_stop_to_generate" src="https://user-images.githubusercontent.com/62595275/229788868-b47fdaf9-45c0-40c6-892e-1269bfa786b9.png">

**Comment by LxDevelop** [comment]
i have to stop manually

**Comment by JetRunner** [comment]
Sometimes it gets a hiccup like this and please start a new conversation to fix it.
